export const initialState = {
  _id: "",
  accountNumber: "",
  firstName: "",
  lastName: "",
  email: "",
  emailVerified: false,
  phoneNumber: "",
  balance: 0,
  dateOfBirth: "",
  photo: "",
  address: "",
  state: "",
  isAdmin: false,
  isOwner: false,
  signedIn: [],
  lastLoginAt: "",
  lastLogoutAt: "",
  createdAt: "",
  updatedAt: "",
  password: "",
  blockedUntil: 0,
};
